# Generated by Django 4.0.4 on 2022-06-04 14:30

import Homework_27.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(validators=[Homework_27.validators.check_age]),
        ),
    ]
